import os


COOKIE_PATH = os.path.expanduser("~/.claude_cookie.txt")


def run_setup():
    print()
    print("\U0001f525 MENUPAPI-CM Setup")
    print("=" * 40)
    print()
    print("To enable REAL Claude reset timers, create this file:")
    print()
    print(f"  {COOKIE_PATH}")
    print()
    print("It must contain ONE LINE like:")
    print()
    print("  sessionKey=sk-ant-sid02-xxxx; cf_clearance=xxxx; lastActiveOrg=xxxx")
    print()
    print("HOW TO GET IT:")
    print()
    print("  1) Open https://claude.ai/settings/usage in Chrome")
    print("  2) Open DevTools (Cmd+Option+I) -> Network tab")
    print('  3) Click "Refresh usage limits" on the page')
    print("  4) In Network tab, click the request to /api/organizations/.../usage")
    print("  5) Go to Headers -> Request Headers -> copy the 'cookie' value")
    print()
    print("Then create the file:")
    print()
    print(f'  echo "sessionKey=...; cf_clearance=..." > {COOKIE_PATH}')
    print(f"  chmod 600 {COOKIE_PATH}")
    print()
    print("Then run:")
    print()
    print("  cm")
    print()
    print("Or validate:")
    print()
    print("  cm doctor")
    print()
    print("\u26a0\ufe0f  DO NOT paste your cookie into GitHub issues.")
    print("\u26a0\ufe0f  cf_clearance expires -- re-copy from browser when it breaks.")
    print()
